### ISSUE TITLE
Cadastro/login de Usuário

### ISSUE THREAD

**Issue by devscheffer** [devscheffer/SenacRS-Projeto-Desenvolvimento#69]
Usuário deve conserguir se cadastrar usando:

| campo | type   |
| ----- | ------ |
| Email | string |
| Senha | string |

-   [x] #70
-   [x] #71
-   [x] #118
-   [x] #104 
-   [x] #130
- [x] #134

**Comment by laaths** [comment]
Concluído dataset de Cadastro/login
